DROOP-752: Fix compatibility issues
droptica/droopler pull request #812
Opened 2022-06-20 11:49 UTC by tadeusz-bronczyk-droptica

Drupal 9.4 compatibility fixes.

2022-06-20 11:52 UTC, tadeusz-bronczyk-droptica commented
`59 | ERROR | Type hint "array" missing for $element`
It has to be without type hint due to problem with:
```
Declaration of Drupal\d_color\Element\ColorElement::preRenderColor(array $element) should be compatible with Drupal\Core\Render\Element\Color::preRenderColor($element) in include()
```

2022-06-24 07:11 UTC, grzegorz-pietrzak-droptica approved these changes

2022-06-24 07:14 UTC, grzegorz-pietrzak-droptica requested changes
Po usunięciu tego `array` musimy jeszcze wstawić komentarz ignorujący tę linijkę w CodeSnifferze, inaczej mamy czerwony pileline.

`// phpcs:ignore`

Można też ignornąć konkretnego sniffa:
https://stackoverflow.com/questions/4306304/ignore-code-snippets-in-php-codesniffer

2022-06-27 10:14 UTC, grzegorz-pietrzak-droptica approved these changes

2022-06-27 10:15 UTC, merged