DROOP-1026: Fixed wrong type declarations in ProviderManager
droptica/droopler pull request #852
Opened 2023-12-14 22:59 UTC by michal-odorski-droptica

2023-12-20 12:06 UTC, js-droptica requested changes

2023-12-20 12:06 UTC, jsamulski commented on modules/custom/d_media/src/Service/ProviderManager.php
> +      assert($provider_plugin instanceof ProviderPluginInterface);
Is it necessary here? The method will throw exception anyway if the return type will be different than `ProviderPluginInterface`

2023-12-20 21:25 UTC, michal-odorski-droptica commented on modules/custom/d_media/src/Service/ProviderManager.php
> +      assert($provider_plugin instanceof ProviderPluginInterface);
PHPstorm warns me that `\Return value is expected to be '\Drupal\d_media\Plugin\Provider\ProviderPluginInterface|false', 'object' returned.` But you're right, maybe I'm being too cautious.

2023-12-21 08:55 UTC, js-droptica approved these changes

2023-12-21 08:55 UTC, merged